tparviainen/clashofclans

- src/ClashOfClans/Models/ClanWarLeagueWar.cs
- src/ClashOfClans/Models/CurrentWar.cs
- src/ClashOfClans/Models/WarBase.cs
I've created the WarBase class and included it in it's own PR as you requested.
Luke
> Added WarBase, parent of ClanWarLeagueWar and CurrentWar

- src/ClashOfClans.Tests/AppSettings.test.json
- src/ClashOfClans.Tests/ClansTests.cs
- src/ClashOfClans.Tests/ClashOfClansLogger.cs
- src/ClashOfClans.Tests/DumpExtensions.cs
- src/ClashOfClans.Tests/PlayersTests.cs
- src/ClashOfClans.Tests/TestsBase.cs
- src/ClashOfClans.Tests/ValidatorTests.cs
Improves the performance of the unit tests by execution requests in parallel. Improves the coverage of unit tests to cover more clans/players including those given in the configuration file.
> Unit test perf improvements

- src/ClashOfClans.Tests/ClansTests.cs
- src/ClashOfClans.Tests/ValidatorTests.cs
- src/ClashOfClans/Validation/ClanTagValidator.cs
- src/ClashOfClans/Validation/Constants.cs
- src/ClashOfClans/Validation/PlayerTagValidator.cs
- src/ClashOfClans/Validation/QueryClansValidator.cs
- src/ClashOfClans/Validation/WarTagValidator.cs
This PR will move all "magic values" to one file as constants that can be referenced via variable name in source code.
> Declare values as constants

- src/ClashOfClans.App/ClansExamples.cs
- src/ClashOfClans.App/LeaguesExamples.cs
- src/ClashOfClans.App/LocationsExamples.cs
- src/ClashOfClans.App/PlayersExamples.cs
- src/ClashOfClans.App/Program.cs
Refactors examples to separate classes based on the used API group. Each example is a "standalone" and can be copy/pasted and executed.
> Refactor examples

- src/ClashOfClans.Tests/ValidatorTests.cs
- src/ClashOfClans/Core/AutoValidatedRequest.cs
This will implement #17 and will only accept LabelIds that follow accepted format.
> Adds validation for LabelIds

- build/version.txt
- src/ClashOfClans.Tests.Integration/AppSettings.test.json
- src/ClashOfClans.Tests.Integration/PlayersTests.cs
- src/ClashOfClans.Tests.Integration/TestsBase.cs
- src/ClashOfClans/ClashOfClansClient.cs
- src/ClashOfClans/Core/AutoValidatedRequest.cs
- src/ClashOfClans/Core/ClashOfClansException.cs
- src/ClashOfClans/Core/ClashOfClansOptions.cs
- src/ClashOfClans/Core/ClashOfClansOptionsInternal.cs
- src/ClashOfClans/Core/GameData.cs
- src/ClashOfClans/Core/Net/ApiEndpoint.cs
- src/ClashOfClans/Core/ThrottleRequestsPerSecond.cs
- src/ClashOfClans/Search/Query.Base.cs
- src/ClashOfClans/Search/Query.cs
- Closes #28: Support multiple tokens via ClashOfClansClient API
- Remove braces from single line statement blocks
- Change continuation time to use ticks instead of milliseconds for better accuracy
> Support multiple tokens via client API

- src/ClashOfClans.Tests.Integration/ClansTests.cs
- src/ClashOfClans.Tests.Integration/LabelsTests.cs
- src/ClashOfClans.Tests.Integration/LocationsTests.cs
- src/ClashOfClans.Tests.Integration/ValidatorTests.cs
- src/ClashOfClans.Tests.Unit/ClashOfClansExceptionTests.cs
- src/ClashOfClans.Tests.Unit/QueryTests.cs
- src/ClashOfClans.Tests.Unit/ThrottleRequestsPerSecondTests.cs
- src/ClashOfClans.Tests.Unit/ValidatorTests.cs
This PR addressess the issue #34
> Harmonize test method names

- build/build.ps1
- build/functions.ps1
- build/version.txt
- src/ClashOfClans.Models/ClashOfClans.Models.csproj
- src/ClashOfClans/ClashOfClans.csproj
- src/ClashOfClans/ClashOfClans.nuspec
Adds a support for Source Link (see https://github.com/dotnet/sourcelink).
> Add support for Source Link

- build/version.txt
- src/ClashOfClans.Models/ClanWarAttack.cs
- src/ClashOfClans.Models/Enums/Status.cs
- src/ClashOfClans.Models/VerifyTokenRequest.cs
- src/ClashOfClans.Models/VerifyTokenResponse.cs
- src/ClashOfClans.Tests.Integration/PlayersTests.cs
- src/ClashOfClans/Api/Players.cs
- src/ClashOfClans/Core/AutoValidatedRequest.cs
- src/ClashOfClans/Core/GameData.cs
- src/ClashOfClans/Core/Net/ApiEndpoint.cs
- src/ClashOfClans/Core/Serialization/MessageSerializer.cs
- src/ClashOfClans/IPlayers.cs
- Implementation for API token verification
- Add Duration property to ClanWarAttack
> Add support for player API token verification

- README.md
- build/version.txt
- src/ClashOfClans.Models/Clan.cs
- src/ClashOfClans.Models/GoldPassSeason.cs
- src/ClashOfClans.Models/Language.cs
- src/ClashOfClans.Models/PlayerItemLevel.cs
- src/ClashOfClans.Tests.Integration/GoldPassTests.cs
- src/ClashOfClans/Api/GoldPass.cs
- src/ClashOfClans/ClashOfClansClient.cs
- src/ClashOfClans/IClashOfClans.cs
- src/ClashOfClans/IGoldPass.cs
New APIs:
- Support for GoldPassSeason API
New model:
- Language
New properties for models:
- Clan.RequiredVersusTrophies
- Clan.RequiredTownhallLevel
- Clan.ChatLanguage
- PlayerItemLevel.SuperTroopIsActive
> Spring 2021 update

- .gitattributes
- .gitignore
- Dockerfile
- README.md
- eng/init.ps1
- notebooks/0-README.ipynb
- notebooks/1-Clans.ipynb
- notebooks/2-Locations.ipynb
- notebooks/3-Leagues.ipynb
- notebooks/4-Players.ipynb
- notebooks/5-Labels.ipynb
- notebooks/6-Gold-Pass.ipynb
Adds a binder support for example notebooks.
> Add Binder + notebooks

- README.md
- build/version.txt
- src/ClashOfClans.Models/ClanWar.cs
- src/ClashOfClans.Models/ClanWarLogEntry.cs
- src/ClashOfClans.Models/Enums/WarPreference.cs
- src/ClashOfClans.Models/Player.cs
Adds a support for new properties:
- ClanWar.AttacksPerMember
- ClanWarLogEntry.AttacksPerMember
- Player.WarPreference (in/out)
> Autumn 2021 update

- README.md
- src/ClashOfClans/ClashOfClans.nuspec
- Add README.md to ClashOfClans.nuspec-file
- Update README.md so that it is suitable for NuGet.org
> Make README.md suitable for NuGet.org

- src/ClashOfClans/ClashOfClans.csproj
- src/ClashOfClans/Search/Query.Base.cs
- src/ClashOfClans/Search/Query.cs
- src/ClashOfClans/Search/QueryClans.cs
Use QueryStringGenerator NuGet package (https://github.com/tparviainen/query-string-generator) for generating query string methods from Query and QueryClans classes instead of using reflection during runtime.
> Use source generator for query string

- build/version.txt
- src/ClashOfClans.Models/Clan.cs
- src/ClashOfClans.Models/ClanCapital.cs
- src/ClashOfClans.Models/ClanDistrictData.cs
- src/ClashOfClans.Models/ClanDistrictDataList.cs
- src/ClashOfClans.Models/Player.cs
- src/ClashOfClans.Tests.Integration/ClashOfClans.Tests.Integration.csproj
- src/ClashOfClans.Tests.Unit/ClashOfClans.Tests.Unit.csproj
- This PR adds a support for **Clan Capital** data for a clan and individual player (contributions).
- Updates Microsoft.NET.Test.Sdk NuGet packages
> Add support for Clan Capital

- build/version.txt
- src/ClashOfClans.Models/ClanCapitalRaidSeason.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonAttack.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonAttackList.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonAttackLogEntry.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonAttackLogList.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonAttacker.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonClanInfo.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonDefenseLogEntry.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonDefenseLogList.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonDistrict.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonDistrictList.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonMember.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonMemberList.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasons.cs
- src/ClashOfClans.Models/Enums/ClanCapitalRaidSeasonState.cs
- src/ClashOfClans.Tests.Integration/ClansTests.cs
- src/ClashOfClans/Api/Clans.cs
- src/ClashOfClans/IClans.cs
- Adds a support for API to retrieve clan's capital raid seasons
- Adds integration tests to retrieve clan's capital raid seasons
> Add "Retrieve clan's capital raid seasons" API

- build/version.txt
- src/ClashOfClans.App/ClashOfClans.App.csproj
- src/ClashOfClans.Blazor/ClashOfClans.Blazor.csproj
- src/ClashOfClans.Models/CapitalLeague.cs
- src/ClashOfClans.Models/Clan.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonAttack.cs
- src/ClashOfClans.Models/ClanCapitalRaidSeasonDistrict.cs
- src/ClashOfClans.Models/ClanMember.cs
- src/ClashOfClans.Models/Enums/PlayerHouseElementType.cs
- src/ClashOfClans.Models/Player.cs
- src/ClashOfClans.Models/PlayerHouse.cs
- src/ClashOfClans.Models/PlayerHouseElement.cs
- src/ClashOfClans.Models/PlayerHouseElementList.cs
- src/ClashOfClans.Tests.Integration/ClashOfClans.Tests.Integration.csproj
- src/ClashOfClans.Tests.Unit/ClashOfClans.Tests.Unit.csproj
- .NET6 to .NET7
- Support for Capital League properties
- Support for Player House properties
> Add Capital League and Player House

- build/version.txt
- src/ClashOfClans.Models/CapitalLeagueList.cs
- src/ClashOfClans.Models/ClanCapitalRanking.cs
- src/ClashOfClans.Models/ClanCapitalRankingList.cs
- src/ClashOfClans.Tests.Integration/LeaguesTests.cs
- src/ClashOfClans.Tests.Integration/LocationsTests.cs
- src/ClashOfClans.Tests.Integration/TestsBase.cs
- src/ClashOfClans/Api/Leagues.cs
- src/ClashOfClans/Api/Locations.cs
- src/ClashOfClans/ILeagues.cs
- src/ClashOfClans/ILocations.cs
Closes #120, new capital APIs:
- League: GetCapitalLeaguesAsync, GetCapitalLeagueAsync
- Location: GetClanCapitalRankingAsync
> Add support for capital league APIs

- build/version.txt
- src/ClashOfClans.Models/ClanMember.cs
- This will fix the missing property, see #174
> fix: Add TownHallLevel property to ClanMember

- src/ClashOfClans.Models/Player.cs
- src/ClashOfClans.Models/PlayerItemLevel.cs
- Add support for new property HeroEquipment
> feat: #176 Add support for Hero equipment
